-- ============================================
-- SENTENCIAS BASICAS DEL LENGUANE SQL
-- ============================================


-- ============================================
-- SENTENCIAS DML
-- ============================================

-- SELECT 
-- Para consultar datos
/*

SELECT <COLUMNAS>
FROM ESQUEMA.TABLA
WHERE <FILTRO>;

*/


SELECT * 
FROM SCOTT.EMP;


SELECT * 
FROM SCOTT.EMP;


SELECT * 
FROM SCOTT.EMP
WHERE SAL > 2000 AND SAL < 5000;


SELECT * 
FROM RECURSOS.EMPLEADO
WHERE SUELDO > 2000 AND SUELDO < 5000;






